version: '3'

services:
  rocker:
    image: osmosisfoundation/rocker:latest
    build:
      context: ./rocker
      args:
        - NONMEM_ZIP_PASS_73=${NONMEM_ZIP_PASS_73}
        - NONMEM_ZIP_PASS_74=${NONMEM_ZIP_PASS_74}
    ports:
      - 8787:8787
    volumes:
      - ./data:/home/rstudio
      - ./license:/opt/nm/license
    environment:
      ROOT: 'TRUE'
  piranajs:
    image: osmosisfoundation/piranajs:latest
    build: 
      context: ./piranajs
    ports:
      - 8000:8000
    volumes:
      - ./license:/opt/nm/license
      - ./license:/opt/pirana/license
      - ./data:/data
    depends_on:
      - psn
  psn:
    image: osmosisfoundation/psn:latest
    build: ./psn
    volumes:
      - ./license:/opt/nm/license
      - ./data:/data
    environment:
      NUM_THREADS: '4'
    depends_on:
      - nonmem
  nonmem:
    image: osmosisfoundation/nonmem:latest
    build:
      context: ./nonmem
      dockerfile: 74.Dockerfile
      args:
        - NONMEM_ZIP_PASS_73=${NONMEM_ZIP_PASS_73}
        - NONMEM_ZIP_PASS_74=${NONMEM_ZIP_PASS_74}
    volumes:
      - ./license:/opt/nm/license
      - ./data:/data

