version: '3'

services:
  rocker:
    image: osmosisfoundation/rocker:local
    build:
      context: ./rocker
      args:
        - NONMEM_ZIP_PASS_73=YOURPASSHERE
        - NONMEM_ZIP_PASS_74=YOURPASSHERE
    ports:
      - 8787:8787
    volumes:
      - ./data:/home/rstudio
      - ./license:/opt/nm/license
    environment:
      - ROOT=TRUE
  piranajs:
    image: osmosisfoundation/piranajs:local
    build: 
      context: ./piranajs
    ports:
      - 8000:8000
    volumes:
      - ./license:/opt/nm/license
      - ./license:/opt/pirana/license
      - ./data:/data
    depends_on:
      - psn
  psn:
    image: osmosisfoundation/psn:local
    build: ./psn
    volumes:
      - ./license:/opt/nm/license
      - ./data:/data
    depends_on:
      - nonmem
  nonmem:
    image: osmosisfoundation/nonmem:local
    build:
      context: ./nonmem
      dockerfile: 73.Dockerfile
      args:
        - NONMEM_ZIP_PASS_73=YOURPASSHERE
        - NONMEM_ZIP_PASS_74=YOURPASSHERE
    volumes:
      - ./license:/opt/nm/license
      - ./data:/data

